/*
 *  CustomizedEnumType.h
 *  Eyecon
 *
 *  Created by PhongLe on 3/11/11.
 *  Copyright 2011 Appo CO., LTD. All rights reserved.
 *
 */

/*****************************************************************
 *							ENUM
 *****************************************************************/

typedef enum _ALERT_CODE
{
    ALERT_USER_LOGIN_ERROR = 1,
    ALERT_PLAYBACK_DRAWER_NOPHOTO = 2,
    ALERT_SIGNUP_GENERICE_ERROR = 3,
    ALERT_LOGIN_CONFIRM = 4,
    ALERT_LINKSOURCE_SUCC = 5,
    ALERT_LINKSOURCE_CONFLICTACCOUNT = 6,
    ALERT_LINKSOURCE_FAILED = 7,
    ALERT_LINKSOURCE_CONFIRM = 8,
    ALERT_UNLINKSOURCE_CONFIRM = 9,
    ALERT_COMMENTING_CHECKINPUT = 10,
    ALERT_EXITMULTITAG_CONFIRM = 11,
    ALERT_POSTCOMMENT_INFO = 12,
}ALERT_CODE;


typedef enum
{
	RENDERER_SUPPORT_ALL,
	RENDERER_SUPPORT_NONE,
	RENDERER_SUPPORT_VIDEO,
	RENDERER_SUPPORT_AUDIO,
	RENDERER_SUPPORT_IMAGE
} RENDERER_SUPPORT_MIMETYPE;

//define block's type
typedef enum
{
	BLOCK_SEARCH,
	BLOCK_RESULT,
	BLOCK_PLAYER,
	BLOCK_PICK,
	BLOCK_PLUG
} BLOCK_TYPE;

//define playback's types
typedef enum
{
	PLAYBACK_PLAYNEWLIST,
    PLAYBACK_PLAYNEWLISTWITHITEM,
    PLAYBACK_PLAYITEMINCURRENTLIST,
    PLAYBACK_PLAYCURRENTLISTTOOTHERPLAYER,
    PLAYBACK_PLAYCURRENTITEM,
	PLAYBACK_PLAY,
	PLAYBACK_PAUSE,
	PLAYBACK_STOP,
    PLAYBACK_FORCE_STOP,
	PLAYBACK_NEXT,
	PLAYBACK_PREV,
	PLAYBACK_MUTE,
	PLAYBACK_UNMUTE,
	PLAYBACK_SETVOLUME,
	PLAYBACK_GETVOLUME,
	PLAYBACK_SYNC_AV_STATE,
	PLAYBACK_SYNC_RENDERINGCONTROLSTATE,
	PLAYBACK_STOP_POLLING
} PLAYBACKCOMMAND;

typedef enum 
{
	RENDERINGCONTROL_UNKNOWN,
	RENDERINGCONTROL_VOLUME_CHANGED,
	RENDERINGCONTROL_MUTE_CHANGED,
	RENDERINGCONTROL_SYNCSTATE
} RENDERINGCONTROLSTATE;

typedef enum 
{
	AVUNKNOWN,
	POSITIONINFO,
	TRANSPORTINFO
} AVTRANSPORTSTATE;

typedef enum {
	WEB_SEARCH,
	LOCAL_SEARCH,
	PREMIUM_SEARCH
}SOURCE_TYPE;

typedef enum {
	NotReachable = 0,
	ReachableViaWiFi,
	ReachableViaWWAN,
	ReachableChangedIPAddress
} NetworkStatus;

enum {
	RESULT_APPENDER_TAIL,
	RESULT_APPENDER_INTERLEAVE
};

//Analytics
typedef enum {
	APPLIFECYCLE_CATEGORY,
	SESSIONLIFECYCLE_CATEGORY,
	SEARCH_CATEGORY,
	PREVIEW_CATEGORY,
	PLAYBACKDEVICE_CATEGORY,
	PLUGLIST_CATEGORY,
	PICKLIST_CATEGORY,
	SOURCEACCOUNTMANAGEMENT_CATEGORY,
	BROWSE_CATEGORY,
	EXCEPTION_CATEGORY
} ANALYTICSCATEGORY;

//log event
typedef enum {
    RATE_EVENT,
    TAG_EVENT,
    GLOBALSEARCH_EVENT,
	INSTALL_EVENT,
	UPDATE_EVENT,
	UNINSTALL_EVENT,
	LOGIN_EVENT,
	LOGOUT_EVENT,
	PREVIEW_EVENT,
	PLAY_EVENT,
	STOP_EVENT,
	PAUSE_EVENT,
	MUTE_EVENT,
	VOLUME_EVENT,
	ADD_EVENT,
	REMOVE_EVENT,
	REORDER_EVENT,
	ASSOCIATE_EVENT,
	DISASSOCIATE_EVENT,
	BROWSE_EVENT,
	EXCEPTION_EVENT
} LOG_EVENT;

/**
 *	Impersonation policy
 */
typedef enum
{
	WHEN_NEEDED,
	ALWAYS,
	NEVER
} IMPERSONATIONPOLICY;

/**
 *	TuneIn type
 */
typedef enum
{
	TYPE_ICY,
	TYPE_PLAYLIST
} TUNEIN_URL_TYPE;

typedef enum {
	FOREVER,
	FADEBYAGE,
	FADEBYACTIVE
}STORE_MODE;

typedef enum 
{
	SETTING_UNKNOWN,
	SETTING_EXPOSEDLOCALPLAYER,
} SETTING_TYPE;

typedef enum
{
	CONTROL_UNKNOWN,
	CONTROL_SWITCH,
	CONTROL_BUTTON
} CONTROL_TYPE;

typedef enum
{
    STATERELVARIABLE_UNKNOWN,
    STATERELVARIABLE_SAMEVALUE,
    STATERELVARIABLE_DIFFVALUE
} STATERELVARIABLE_STATE;

typedef enum
{
	LEVEL_DEBUG,
	LEVEL_INFO,
	LEVEL_WARNING,
	LEVEL_ERROR
} LEVEL_LOG;

typedef enum
{
	STATUS_OK,
	STATUS_WARNING,
	STATUS_ERROR
} EVENTSTATUS;

typedef enum
{
	DEVICE_UNDEFINEDEVENT,
    DEVICE_JOINT,
	DEVICE_LEFT,
    DEVICE_REMOVE_ALL,
    ONLINE_CHANNEL_JOINT,
    ONLINE_CHANNEL_LEFT,
	SERVERDEVICE_JOINT,
	SERVERDEVICE_LEFT,
    RENDERERDEVICE_JOINT,
	RENDERERDEVICE_LEFT,
	DEVICE_UPDATED,
	DEVICE_SOURCEPROTOCOLINFO,
	DEVICE_SINKPROTOCOLINFO,
	DEVICE_BROWSE_RESPONSE,
	DEVICE_SEARCH_RESPONSE,
	RENDERINGCONTROL_EVENT,
	PLAYBACK_EVENT,
    AIRPLAY_JOINT,
    AIRPLAY_REMOVEALL,
    
    /* IPAD UI Events */
    IPAD_UI_NAVIGATOR_RESIZE_THUMBNAIL,
    IPAD_UI_NAVIGATOR_RESIZE_NORMAL,
    
    IPAD_UI_NAVIGATOR_MENU_CLICKED,
    IPAD_UI_PROFILE_ICON_CLICKED,
    IPAD_UI_PROFILE_FRIENDS_CLICKED,
    IPAD_UI_PROFILE_FOLLOWERS_CLICKED,
    IPAD_UI_PROFILE_FOLLOWING_CLICKED
    
} EVENTTYPE;

typedef enum
{
    CHANNEL_UI,
    CHANNEL_DEVICE,
    CHANNEL_PLAYBACK,
    CHANNEL_LOCALPLAYBACK,
    CHANNEL_TRACKINGLOG,
    CHANNEL_MASTERPLAYBACK,
    CHANNEL_AVSTREAM,
    CHANNEL_PHOTOSTREAM,
    CHANNEL_SIGNUP,
    CHANNEL_SIGNOUT,
    CHANNEL_LOGINCONTEXT,
} CHANNEL_PIPE;

typedef enum NAVIGATION_TYPE
{
    NAVIGATION_PUSH = 0,
    NAVIGATION_POPTOP = 1,
    NAVIGATION_PUSHAFTERPOPTOROOT = 2,
    NAVIGATION_PUSHPLAYBACK = 3,
    NAVIGATION_PUSHSIBLINGCONTROL=4,
    NAVIGATION_PUSHTOPARENTCONTROL=5,
    NAVIGATION_SETTING_MENU=6,
    NAVIGATION_PUSHPLAYBACKFROMAUTOCOMPLETE=7,
    NAVIGATION_PUSHPHOTOGRID=8,
    NAVIGATION_POPPHOTOGRID=9,
    NAVIGATION_SELECT_ITEMS=10
}NAVIGATION_TYPE;

typedef enum SCREEN_TAG {
    SCREEN_UNKNOW,
    LOGIN_SCREEN_TAG,
    MENU_CLOSE_FAKE_TAG = 1,
    TIMELINE_SCREEN_TAG = 100,
    HASHTAG_LIST_SCREEN_TAG,
    TAGLIST_SCREEN_TAG,
    MYTAGLIST_FRIENDTAGLIST_SCREEN_TAG,
    FRIENDTAGLIST_SCREEN_TAG,
    GROUP_SCREEN_TAG,
    FILTER_SCREEN_TAG,
    MY_HISTORY_SCREEN_TAG,
    FRIENDS_GROUP_SCREEN_TAG,
    FOLLOW_FOLLWER_SCREEN_TAG,
    MYFRIEND_SCREEN_TAG,
    FOLLOWERS_SCREEN_TAG,
    FOLLOWING_SCREEN_TAG,
    MYGROUP_SCREEN_TAG,
    MUSIC_SCREEN_TAG,
    PHOTO_SCREEN_TAG,
    VIDEO_SCREEN_TAG,
    BROWSE_SCREEN_TAG,
    USER_SETTING_SCREEN_TAG,
    GLOBAL_SEARCH_SCREEN_TAG,
    SEARCH_RESULT_SCREEN_TAG,
    SEARCH_SCREEN_TAG,    
    PLAYER_LIST_SCREEN_TAG,
    CHANNEL_LIST_SCREEN_TAG,
    MEDIA_OBJECT_LIST_SCREEN_TAG,
    TABBED_MEDIA_LIST_SCREEN_TAG,
    SEARCHABLE_MEDIA_OBJECT_LIST_SCREEN_TAG,
    SEARCHABLE_BROWSE_RESULT_LIST_SCREEN_TAG,
    TABBED_MEDIA_GRID_SCREEN_TAG,
    SEARCHABLE_MEDIA_OBJECT_GRID_SCREEN_TAG,
    SEARCHABLE_MEDIA_OBJECT_GRID_WITHOUT_SEARCHBAR_SCREEN_TAG,
    BROWSE_PHOTOS_GRID_SCREEN_TAG,
    GLOBAL_SEARCHDETAIL_SCREEN_TAG,
    PEOPLE_SEARCHABLE_MEDIA_OBJECT_LIST_SCREEN_TAG,
    GLOBAL_TAGSEARCHDETAIL_SCREEN_TAG,
    TAGCONTENT_SCREEN_TAG,
    
    GROUP_FILTER_SCREEN_TAG,
    GROUPLIST_FILTER_SCREEN_TAG,
    MEDIA_FILTER_SCREEN_TAG,
    
    GROUP_FILTER_SCREEN_TAG_POPOVER,
    GROUPLIST_FILTER_SCREEN_TAG_POPOVER,
    MEDIA_FILTER_SCREEN_TAG_POPOVER,
    
    MEDIALINK_DETAIL_SCREEN_TAG,
    ADDGROUP_SCREEN_TAG,
    ADDFRIENDSINGROUP_SCREEN_TAG,
    FRIENDSINGROUP_SCREEN_TAG,
    PERSON_PROFILE_SCREEN_TAG,
    ME_PROFILE_SCREEN_TAG,
    PLAYBACK_SCREEN_TAG,
    UPNPPLAYBACK_SCREEN_TAG,
    REMOVE_TOP_SCREEN_TAG,
    ACCOUNT_SETTING_SCREEN_TAG,
	PRIVACY_SETTING_SCREEN_TAG,
	PUBLISHING_SETTING_SCREEN_TAG,
	ONLINE_ACCOUNT_SETTING_SCREEN_TAG,
	DEVICES_SETTING_SCREEN_TAG,
	VISIBLE_TO_ORTHERS_SCREEN_TAG,
	WHO_CAN_SEE_SCREEN_TAG,
	TERMS_OF_SERVICE_SCREEN_TAG,
	PRIVACY_POLICY_SCREEN_TAG,
	ABOUT_SCREEN_TAG,
	FEEDBACK_SCREEN_TAG,
    ADDTAG_SCREEN_TAG,
    ADDCOMMENT_SCREEN_TAG,
    ADD_MULTITAG_SCREEN_TAG,
    GROUPLIST_SETTING_SCREEN_TAG,
	SOURCE_SETTING_SCREEN_TAG,
    LOCALPLAYBACK_SCREEN_TAG,
    COMINGUP_SCREEN_TAG,
    INTEGRATEDALERT_LINK_SCREEN_TAG,
    MAIL_APPLICATION_SCREEN,
    MAIL_WITH_TO_APPLICATION_SCREEN,
    MAIL_INVITEFRIEND_APPLICATION_SCREEN,
    FACEBOOKFRIEND_SCREEN_TAG,
    COMPOSE_INVITEFRIEND_SCREEN_TAG,
    ALERT_LOGOUT_UNAUTHORIZED_ACCOUNT,
    FEATUREDMEDIA_SCREEN_TAG,
    PERSONAL_ACCESS_AUTHORIZE_SCREEN_TAG,
    FACEBOOK_LOGINREQUEST_SCREEN
}SCREEN_TAG;

typedef enum ACTION_POPOVER_TAG {
    ACTION_CLOSE = 0,
    ACTION_WATCHON = 1,
    ACTION_WATCHWITH = 2,
    ACTION_COMMENT = 4,
    ACTION_COMINGUP = 8,
    ACTION_ADDTAGLIST = 16,
    ACTION_FILTER = 32
} ACTION_POPOVER_TAG;

typedef enum
{
    SOURCE_UNKNOWN = 10,
    SOURCE_INTERNET,
    SOURCE_TOPPICK,
    SOURCE_LOCALLIBRARY
} SOURCE_CATEGORY;

typedef enum
{
    PEOPLE_EVERYONE = 1,
    PEOPLE_ME,
    PEOPLE_ME_AND_MY_FRIENDS_AND_FOLLOWING,
    PEOPLE_GROUP_LIST
} PEOPLE_SCOPE;

typedef enum
{
   EVERYONE = 1,
   ME = 2,
   FOLLOWING = 4, 
} TAGLIST_GROUP_FILTER;

typedef enum {
    UNKNOWN = 0,
    VIDEO = 1,
	AUDIO = 2 ,

	PHOTO = 4,
	ALL   = 7
} MEDIATYPE;

typedef enum
{
    MEDIAITEM_MIMETYPE_VIDEO = 1,
    MEDIAITEM_MIMETYPE_AUDIO = 2,

    MEDIAITEM_MIMETYPE_IMAGE = 4,
    MEDIAITEM_MIMETYPE_ALL   = 7
}MEDIAITEM_MIEMETYPE;

typedef enum
{
    SEARCH_VIDEO = 1,
    SEARCH_AUDIO = 2,

	SEARCH_PHOTO = 4,
    SEARCH_ALL   = 7,
} SEARCHTYPE; 

typedef enum
{
    CAT_VIDEO       = 1, 
    CAT_MUSIC       = 2,
   
    CAT_PHOTO       = 4,
    
    CAT_HASHTAG     = 8,
    CAT_PEOPLE      = 16,

    CAT_ALL			= 31
} MEDIA_CATEGORY;

typedef enum
{
    LOW_PRIORITY,
    NORMAL_PRIORITY,
    HIGH_PRIORITY
} THREAD_PRIORITY;

typedef enum
{
    MEDIA_ABSTRACT,
    MEDIA_ITEM,
    MEDIA_CONTAINER,
    MEDIA_LINK,
    MEDIA_PEOPLE,
    MEDIA_HASHTAG,
    MEDIA_ACTIVITY,
    MEDIA_COMMENT
} MEDIAOBJECTTYPE;

typedef enum
{
    CONTAINER_UNKNOWN,
    CONTAINER_DEFAULT,
    CONTAINER_IMAGE,
    CONTAINER_MUSIC,
    CONTAINER_VIDEO,
    CONTAINER_AUDIO,
    CONTAINER_PERSON,
    CONTAINER_FOLDER = CONTAINER_DEFAULT
} CONTAINER_TYPE;

typedef enum
{
    ALERTTAG_SUGGEST_LOGINWITHFACEBOOK=50,
    ALERTTAG_GROUPLIST_NOGROUP,
    ALERTTAG_GROUPLIST_NOSELECTION,
    ALERTTAG_GROUP_ADDGROUP,
    ALERTTAG_GROUP_REMOVELASTFRIEND,
    ALERTTAG_GROUP_ADDCOMMENT,
    ALERTTAG_SUGGEST_SETUPMAILACCOUNT,
    ALERTTAG_ASK_PLAYON_LOCALDEVICE,
    ALERTTAG_CONNECT_PERSONALACCESS,
    ALERTTAG_DISCONNECT_PERSONALACCESS,
    ALERTTAG_SETUP_TWITTER_SETTING,
    ALERTTAG_LOGOUT,
    ALERTTAG_ADDTAGLIST
}ALERTTAGS;

typedef enum
{
    FILTER_UNKNOWN,
    FILTER_GROUP,
    FILTER_MEDIA,
    FILTER_GROUPLIST
} FILTER_TYPE;

typedef enum
{
    NAVIGATIONBAR_EMPTY = 0,
    NAVIGATIONBAR_BACK = 1,
    NAVIGATIONBAR_BTNPROFILE = 2,
    NAVIGATIONBAR_CANCEL = 4,
    NAVIGATIONBAR_DONE = 8,
    NAVIGATIONBAR_FILTER = 16,
    NAVIGATIONBAR_INVITE = 32,
    NAVIGATIONBAR_MENU = 64,
    NAVIGATIONBAR_SELECTITEMS = 128,
    NAVIGATIONBAR_SEND = 256,
    NAVIGATIONBAR_TAG = 512,
    
    //back
    NAVIGATIONBAR_BACK_FILTER_MENU = NAVIGATIONBAR_BACK | NAVIGATIONBAR_FILTER | NAVIGATIONBAR_MENU,
    NAVIGATIONBAR_BACK_INVITE = NAVIGATIONBAR_BACK | NAVIGATIONBAR_INVITE,
    NAVIGATIONBAR_BACK_MENU = NAVIGATIONBAR_BACK | NAVIGATIONBAR_MENU,
    NAVIGATIONBAR_BACK_SEND = NAVIGATIONBAR_BACK | NAVIGATIONBAR_SEND,
    NAVIGATIONBAR_BACK_TAG_MENU = NAVIGATIONBAR_BACK | NAVIGATIONBAR_TAG | NAVIGATIONBAR_MENU, 
    
    NAVIGATIONBAR_BTNPROFILE_FILTER_MENU = NAVIGATIONBAR_BTNPROFILE | NAVIGATIONBAR_FILTER | NAVIGATIONBAR_MENU,
    
    //cancel
    NAVIGATIONBAR_CANCEL_SELECITEMS = NAVIGATIONBAR_CANCEL | NAVIGATIONBAR_SELECTITEMS,
    NAVIGATIONBAR_CANCEL_DONE = NAVIGATIONBAR_CANCEL | NAVIGATIONBAR_DONE,
    
    //done
    NAVIGATIONBAR_DONE_FILTER = NAVIGATIONBAR_DONE | NAVIGATIONBAR_FILTER,
    NAVIGATIONBAR_DONE_TAG = NAVIGATIONBAR_DONE | NAVIGATIONBAR_TAG,
    NAVIGATIONBAR_DONE_INVITE = NAVIGATIONBAR_DONE | NAVIGATIONBAR_INVITE,
    
    
    NAVIGATIONBAR_FILTER_MENU = NAVIGATIONBAR_FILTER | NAVIGATIONBAR_MENU,
    
    NAVIGATIONBAR_TAG_MENU = NAVIGATIONBAR_TAG | NAVIGATIONBAR_MENU,
} NAVIGATIONBAR_TYPE;

typedef enum
{
    FOOTER_EMPTY = 0,
    FOOTER_PLAY = 1,
    FOOTER_MORE = 2,
    
    FOOTER_PLAY_MORE = FOOTER_PLAY | FOOTER_MORE,
} FOOTER_TYPE;

typedef enum
{
    LOCALPLAYBACK_TAG,
    LOCALPLAYBACK_MORE,
    LOCALPLAYBACK_PREV,
    LOCALPLAYBACK_NEXT,
    LOCALPLAYBACK_DONE,
    LOCALPLAYBACK_SCALE,
    LOCALPLAYBACK_MINIMIZE
} EYEC_CUSTOM_PLAYBACKCTRL;

typedef enum
{
    CONTEXT_UNKNOWN,
    CONTEXT_ACTIVITY,
    CONTEXT_BROWSE,
    CONTEXT_TAG,
    CONTEXT_SEARCH
} CONTEXT_TYPE;

typedef enum
{
    SECTION_UNKNOWN,
    SECTION_FRIENDS,
    SECTION_GROUPS,
    SECTION_FOLLOWERS,
    SECTION_FOLLOWING
} SECTION_TYPE;

typedef enum
{
    NAVIGATOR_STATE_NORMAL,
    NAVIGATOR_STATE_THUMBNAIL
}IPAD_NAVIGATOR_STATE;

typedef enum
{
    MEDIALIST_EMPTY = 0,
    MEDIALIST_HAS_ITEM = 1,
    MEDIALIST_HAS_CONTAINER = 2,
    MEDIALIST_HAS_BOTH = 3
} MEDIALIST_TYPE;

typedef enum
{
    SIGNINSTATE_WAITING,
    SIGNINSTATE_CANCEL,
    SIGNINSTATE_LOGIN,
} SIGNINSTATE;

typedef enum
{
    LOGINSTATE_CANCEL,
    LOGINSTATE_NOATHENURL,
    LOGINSTATE_TIMEOUT,
    LOGINSTATE_LOGINFAILED,
    LOGINSTATE_LOGINSUCC
} LOGINSTATE;

typedef enum
{
    PRIVACY_PUBLIC,
    PRIVACY_UNLISTED,
    PRIVACY_PRIVATE
} PRIVACY_MEDIA;

typedef enum {
    CUSTOMSEGMENT_CAPLEFT          = 0,
    CUSTOMSEGMENT_CAPMIDDLE        = 1,
    CUSTOMSEGMENT_CAPRIGHT         = 2,
    CUSTOMSEGMENT_CAPLEFTANDRIGHT  = 3
} CUSTOMSEGMENT_CAPLOCATION;


typedef enum {
    MASTERPLAYBACK_SYNC,
    MASTERPLAYBACK_PLAYERLIST,
    MASTERPLAYBACK_SHOWPLAYBACKCTRL,
    MASTERPLAYBACK_HIDEPLAYBACKCTRL,
    MASTERPLAYBACK_DISPLAYPLAYERS,
    MASTERPLAYBACK_COMMENT_AV,
    MASTERPLAYBACK_COMMENT_PHOTO
} MASTERPLAYBACK_TYPE;

typedef enum
{
    ROLE_GUEST,
    ROLE_USER,
    ROLE_ADMIN,
    ROLE_ARTIST
}USER_ROLE;

typedef enum
{
    OFFLINE,
    ONLINE
}PRESENCE;

typedef enum
{
    NONE,
    FRIEND,
    FOLLOWEE
} RELATIONSHIP;

typedef enum _LOGIN_STATUS
{
    NOT_LOGGEDIN,
    LOGGED_IN
}LOGIN_STATUS;

typedef enum _CATEGORY_TYPE
{
    CATEGORY_UNKNOWN,
    CATEGORY_FEATURED,
    CATEGORY_NEWEST,
    CATEGORY_POPULAR
} CATEGORY_TYPE;

typedef enum _TAGLIST_SCREENTAG
{
    TAGLIST_SCREENTAG_UNKNOWN,
    TAGLIST_SCREENTAG_DISCOVER,
    TAGLIST_SCREENTAG_TAGLIST,
    TAGLIST_SCREENTAG_MYTAGLIST,
    TAGLIST_SCREENTAG_TAGLISTPROFILE,
    TAGLIST_SCREENTAG_USERFEED,
    TAGLIST_SCREENTAG_USERPROFILE,
    TAGLIST_SCREENTAG_SOURCE_BROWSE,
    TAGLIST_SCREENTAG_GLOBAL_SEARCH,
    TAGLIST_SCREENTAG_MEDIA_LIST
} TAGLIST_SCREENTAG;

typedef enum _INTERNETSOURCE_SERVICETYPE
{
    INTERNETSOURCE_UNKNOWN = 0,
    INTERNETSOURCE_MEDIASERVICE = 1,
    INTERNETSOURCE_SOCIALNETWORK = 2,
} INTERNETSOURCE_SERVICETYPE;


typedef enum _ACTION_WAITING {
    ACTION_WAITING_UNKNOWN,
    ACTION_WAITING_MY_TAGLIST,
    ACTION_WAITING_PROFILE,
    ACTION_WAITING_TAG,
    ACTION_WAITING_COMMENT,
    ACTION_WAITING_OPEN_PRIVATE_BROWSE_FOLDER,
    ACTION_WAITING_LINK_SOURCE_ACCOUNT,
    ACTION_WAITING_FOLLOW,
} ACTION_WAITING;